# Generated by Django 5.2.8 on 2025-12-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('identity', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='business_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='business.businessgroup'),
        ),
    ]
