# Generated by Django 5.2.8 on 2025-12-04 11:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_alter_business_options_business_business_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('reserved_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Amount reserved for pending SMS / operations.', max_digits=18)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='business.business')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('TOPUP', 'Top up'), ('SMS_DEBIT', 'SMS debit'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Manual adjustment'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=4, help_text='Wallet balance right after this transaction.', max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, help_text='Optional reference to payment gateway, SMS message id, etc.', max_length=255)),
                ('meta', models.JSONField(blank=True, help_text='Extra JSON metadata (e.g., SMS ID, route, campaign id).', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(help_text="ISO country code (e.g. 'RWA').", max_length=3)),
                ('operator', models.CharField(blank=True, help_text="Optional operator name (e.g. 'MTN', 'Airtel').", max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=4, help_text='Cost per SMS unit in RWF.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, help_text='Null = global default pricing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_prices', to='business.business')),
            ],
            options={
                'verbose_name': 'SMS Price',
                'verbose_name_plural': 'SMS Prices',
                'indexes': [models.Index(fields=['business', 'country', 'operator'], name='billing_sms_busines_1b9c19_idx')],
            },
        ),
    ]
