# Generated by Django 5.2.8 on 2025-12-04 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('business', '0002_alter_business_options_business_business_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprice',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=4, help_text='Price per SMS unit in RWF.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Positive for credit, negative for debit.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('TOPUP', 'Top up'), ('SMS_DEBIT', 'SMS debit'), ('ADJUSTMENT', 'Manual adjustment'), ('COMMISSION', 'Commission earned')], max_length=20),
        ),
        migrations.CreateModel(
            name='SmsCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segments', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=3)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('external_reference', models.CharField(blank=True, help_text='Message id / campaign id / external reference.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_charges', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_generated', to='business.business')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_earnings', to='business.business')),
                ('sms_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='billing.smscharge')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('ADMIN', 'Admin'), ('RESELLER', 'Reseller'), ('CLIENT', 'Client'), ('PAYMENT', 'Payment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResellerCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, help_text='Commission percent (e.g. 15.00 = 15%).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_parents', to='business.business')),
                ('parent', models.ForeignKey(help_text='The reseller / platform that earns commission.', on_delete=django.db.models.deletion.CASCADE, related_name='commission_children', to='business.business')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
