# Generated by Django 5.2.8 on 2025-12-04 15:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_smsprice_price_per_unit_and_more'),
        ('business', '0002_alter_business_options_business_business_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettopup',
            name='business',
        ),
        migrations.RemoveField(
            model_name='wallettopup',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='smsprice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='smsprice',
            name='billing_sms_busines_1b9c19_idx',
        ),
        migrations.RemoveField(
            model_name='smsprice',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_received', to='business.business'),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='sms_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.smscharge'),
        ),
        migrations.AlterField(
            model_name='resellercommission',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_child', to='business.business'),
        ),
        migrations.AlterField(
            model_name='resellercommission',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='resellercommission',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_parent', to='business.business'),
        ),
        migrations.AlterField(
            model_name='smscharge',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='smscharge',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smscharge',
            name='segments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smsprice',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='smsprice',
            name='country',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='smsprice',
            name='operator',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smsprice',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('TOPUP', 'Topup'), ('SMS_DEBIT', 'Sms Debit'), ('COMMISSION', 'Commission'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='reserved_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.DeleteModel(
            name='WalletTopUp',
        ),
    ]
