# Generated by Django 5.2.8 on 2025-12-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_wallettopup_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Optional reference to payment gateway, SMS message id, etc.', max_length=255, null=True),
        ),
    ]
