// Country codes and phone prefixes for registration forms

export const COUNTRIES = [
  { code: "US", name: "United States", prefix: "+1" },
  { code: "GB", name: "United Kingdom", prefix: "+44" },
  { code: "CA", name: "Canada", prefix: "+1" },
  { code: "AU", name: "Australia", prefix: "+61" },
  { code: "NZ", name: "New Zealand", prefix: "+64" },
  { code: "ZA", name: "South Africa", prefix: "+27" },
  { code: "IN", name: "India", prefix: "+91" },
  { code: "KE", name: "Kenya", prefix: "+254" },
  { code: "NG", name: "Nigeria", prefix: "+234" },
  { code: "GH", name: "Ghana", prefix: "+233" },
  { code: "UG", name: "Uganda", prefix: "+256" },
  { code: "TZ", name: "Tanzania", prefix: "+255" },
  { code: "MW", name: "Malawi", prefix: "+265" },
  { code: "ZM", name: "Zambia", prefix: "+260" },
  { code: "ZW", name: "Zimbabwe", prefix: "+263" },
  { code: "SG", name: "Singapore", prefix: "+65" },
  { code: "MY", name: "Malaysia", prefix: "+60" },
  { code: "PH", name: "Philippines", prefix: "+63" },
  { code: "TH", name: "Thailand", prefix: "+66" },
  { code: "VN", name: "Vietnam", prefix: "+84" },
  { code: "DE", name: "Germany", prefix: "+49" },
  { code: "FR", name: "France", prefix: "+33" },
  { code: "ES", name: "Spain", prefix: "+34" },
  { code: "IT", name: "Italy", prefix: "+39" },
  { code: "BR", name: "Brazil", prefix: "+55" },
  { code: "MX", name: "Mexico", prefix: "+52" },
  { code: "AR", name: "Argentina", prefix: "+54" },
  { code: "CL", name: "Chile", prefix: "+56" },
  { code: "AE", name: "United Arab Emirates", prefix: "+971" },
  { code: "SA", name: "Saudi Arabia", prefix: "+966" },
  { code: "EG", name: "Egypt", prefix: "+20" },
  { code: "JP", name: "Japan", prefix: "+81" },
  { code: "CN", name: "China", prefix: "+86" },
  { code: "KR", name: "South Korea", prefix: "+82" },
  { code: "HK", name: "Hong Kong", prefix: "+852" },
  { code: "TW", name: "Taiwan", prefix: "+886" },
  { code: "ID", name: "Indonesia", prefix: "+62" },
  { code: "PK", name: "Pakistan", prefix: "+92" },
  { code: "BD", name: "Bangladesh", prefix: "+880" },
  { code: "LK", name: "Sri Lanka", prefix: "+94" },
];

export const RESELLER_ACCOUNT_TYPES = [
  { value: "BASIC", label: "Basic Reseller", description: "Up to 10 sub-clients" },
  { value: "PROFESSIONAL", label: "Professional", description: "Up to 50 sub-clients" },
  { value: "ENTERPRISE", label: "Enterprise", description: "Unlimited sub-clients" },
];

export const BUSINESS_INDUSTRIES = [
  "Marketing Agency",
  "E-commerce",
  "Financial Services",
  "Healthcare",
  "Education",
  "Telecommunications",
  "Logistics",
  "Retail",
  "Media & Publishing",
  "Travel & Hospitality",
  "Manufacturing",
  "Technology",
  "Other",
];

export const COMPANY_SIZES = [
  "1-10 employees",
  "11-50 employees",
  "51-200 employees",
  "201-500 employees",
  "501-1000 employees",
  "1000+ employees",
];
