# Generated by Django 5.2.8 on 2025-12-01 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('RESELLER', 'Reseller'), ('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('ORGANIZATION', 'Organization')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('industry_category', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Resellers can have multiple client businesses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True)),
                ('favicon', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#0057ff', max_length=20)),
                ('secondary_color', models.CharField(default='#002266', max_length=20)),
                ('dashboard_title', models.CharField(default='WeCall SMS', max_length=200)),
                ('custom_css', models.TextField(blank=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='business.business')),
            ],
            options={
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted to this group', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Business Group',
                'verbose_name_plural': 'Business Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Permission groups assigned to this business', related_name='businesses', to='business.businessgroup'),
        ),
    ]
