# Generated by Django 5.2.8 on 2025-12-01 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['business_name'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AddField(
            model_name='business',
            name='business_username',
            field=models.SlugField(default='Null', help_text="Unique business code: e.g. 'kcb', 'rdb', 'mtnbiz'.", max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Permission groups attached to this business', related_name='businesses', to='business.businessgroup'),
        ),
        migrations.AlterField(
            model_name='business',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Resellers can own multiple client businesses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions granted to this business group', to='auth.permission'),
        ),
    ]
