# Generated by Django 5.2.8 on 2025-12-04 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_alter_business_options_business_business_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('sender', models.CharField(max_length=64)),
                ('recipient', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, help_text='Total charge for this SMS (client cost).', max_digits=12, null=True)),
                ('currency', models.CharField(default='RWF', max_length=16)),
                ('gateway', models.CharField(default='jasmin', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('smpp_message_id', models.CharField(blank=True, help_text='Message ID returned by SMPP.', max_length=128, null=True)),
                ('text', models.TextField(blank=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='business.business')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_sms_messages', to='business.business')),
            ],
        ),
    ]
